[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:xvfb]
command=Xvfb :99 -screen 0 1280x720x24
autostart=true
autorestart=true
priority=1

[program:xfce4]
command=startxfce4
environment=DISPLAY=":99"
autostart=true
autorestart=true
priority=2
startsecs=3

[program:x11vnc]
command=x11vnc -display :99 -nopw -listen localhost -xkb -forever -quiet
autostart=true
autorestart=true
priority=3
startsecs=5

[program:websockify]
command=websockify --web=/usr/share/novnc/ 8080 localhost:5900
autostart=true
autorestart=true
priority=4
startsecs=7

[program:chromium]
command=chromium-browser --display=:99 --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1280,720 https://www.youtube.com
environment=DISPLAY=":99"
autostart=true
autorestart=false
priority=5
startsecs=10
